# S3 Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: default
type: Opaque
data:
  access-key: <base64-encoded-access-key>
  secret-key: <base64-encoded-secret-key>

---
# Azure Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
  namespace: default
type: Opaque
data:
  account-name: <base64-encoded-storage-account-name>
  account-key: <base64-encoded-storage-account-key>

---
# JWT Authentication Secret
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
data:
  token: <base64-encoded-jwt-token>

---
# TLS Secret for Ingress
apiVersion: v1
kind: Secret
metadata:
  name: api-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-certificate>
  tls.key: <base64-encoded-private-key>
