---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlitedatabases.database.sqlite.io
spec:
  group: database.sqlite.io
  names:
    kind: SqliteDatabase
    listKind: SqliteDatabaseList
    plural: sqlitedatabases
    singular: sqlitedatabase
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SqliteDatabase is the Schema for the sqlitedatabases API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of SqliteDatabase
            type: object
            properties:
              database:
                type: object
                description: SQLite database configuration
                properties:
                  name:
                    type: string
                    description: Name of the SQLite database file
                    default: "database.db"
                  initScript:
                    type: string
                    description: Name of ConfigMap containing SQL initialization script
                  storage:
                    type: object
                    description: Storage configuration for the database
                    properties:
                      size:
                        type: string
                        description: Size of the persistent volume
                        default: "1Gi"
                      storageClass:
                        type: string
                        description: Storage class for the persistent volume
              litestream:
                type: object
                description: Litestream replication configuration
                properties:
                  enabled:
                    type: boolean
                    description: Enable Litestream replication
                    default: true
                  replicas:
                    type: array
                    description: List of replication targets
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: ["s3", "azure", "gcs", "local"]
                          description: Type of storage backend
                        bucket:
                          type: string
                          description: Bucket name for S3/GCS or container name for Azure
                        region:
                          type: string
                          description: Region for S3/GCS
                        endpoint:
                          type: string
                          description: Custom S3 endpoint (e.g., wasabisys.com for Wasabi)
                        path:
                          type: string
                          description: Path within the bucket/container
                        credentials:
                          type: object
                          description: Credentials for the storage backend
                          properties:
                            secretName:
                              type: string
                              description: Name of the Secret containing credentials
                            accessKeyField:
                              type: string
                              description: Field name for access key in the secret
                              default: "access-key"
                            secretKeyField:
                              type: string
                              description: Field name for secret key in the secret
                              default: "secret-key"
                        retention:
                          type: string
                          description: Retention period for backups
                          default: "24h"
                        retentionCheckInterval:
                          type: string
                          description: How often to check for expired backups
                          default: "1h"
              sqliteRest:
                type: object
                description: sqlite-rest API configuration
                properties:
                  enabled:
                    type: boolean
                    description: Enable sqlite-rest API
                    default: true
                  port:
                    type: integer
                    description: Port for sqlite-rest API
                    default: 8080
                  authSecret:
                    type: string
                    description: Name of Secret containing JWT token/key
                  allowedTables:
                    type: array
                    items:
                      type: string
                    description: List of tables allowed for API access
                  metrics:
                    type: object
                    description: Metrics configuration
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      port:
                        type: integer
                        default: 8081
              ingress:
                type: object
                description: Ingress configuration for external access
                properties:
                  enabled:
                    type: boolean
                    description: Enable Ingress
                    default: false
                  host:
                    type: string
                    description: Hostname for the Ingress
                  tls:
                    type: object
                    description: TLS configuration
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      secretName:
                        type: string
                        description: Name of TLS secret
              resources:
                type: object
                description: Resource requirements for the pod
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "100m"
                      memory:
                        type: string
                        default: "128Mi"
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "500m"
                      memory:
                        type: string
                        default: "512Mi"
          status:
            description: Status defines the observed state of SqliteDatabase
            type: object
            properties:
              phase:
                type: string
                description: Current phase of the database
                enum: ["Pending", "Running", "Failed", "Terminating"]
              message:
                type: string
                description: Human-readable message about the current status
              replicas:
                type: integer
                description: Number of active replicas
              lastBackup:
                type: string
                format: date-time
                description: Timestamp of the last successful backup
              endpoints:
                type: object
                description: API endpoints information
                properties:
                  rest:
                    type: string
                    description: REST API endpoint URL
                  metrics:
                    type: string
                    description: Metrics endpoint URL
        type: object
    served: true
    storage: true
    subresources:
      status: {}
